// src/app/components/profile/profile.component.ts
import { Component, type OnInit } from "@angular/core"
import { CommonModule } from "@angular/common"
import { type FormBuilder, type FormGroup, Validators, ReactiveFormsModule } from "@angular/forms"
import { MatCardModule } from "@angular/material/card"
import { MatFormFieldModule } from "@angular/material/form-field"
import { MatInputModule } from "@angular/material/input"
import { MatButtonModule } from "@angular/material/button"
import { MatIconModule } from "@angular/material/icon"
import { MatSnackBarModule, type MatSnackBar } from "@angular/material/snack-bar"
import type { AuthService } from "../../services/auth.service"

@Component({
  selector: "app-profile",
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatSnackBarModule,
  ],
  template: `
    <div class="page-container">
      <div class="page-header">
        <h1 class="page-title">Mon profil</h1>
        <p class="page-subtitle">Gérez vos informations personnelles et paramètres de compte</p>
      </div>

      <div class="form-container">
        <mat-card class="content-card">
          <mat-card-header>
            <mat-card-title>Informations du profil</mat-card-title>
          </mat-card-header>
          <mat-card-content>
            <form [formGroup]="profileForm" (ngSubmit)="onSubmit()">
              <div class="form-grid">
                <div class="form-column">
                  <mat-form-field appearance="outline">
                    <mat-label>Login</mat-label>
                    <input matInput formControlName="login" readonly>
                    <mat-icon matSuffix>person</mat-icon>
                  </mat-form-field>

                  <mat-form-field appearance="outline">
                    <mat-label>Email *</mat-label>
                    <input matInput type="email" formControlName="email" required>
                    <mat-icon matSuffix>email</mat-icon>
                    <mat-error *ngIf="profileForm.get('email')?.hasError('required')">
                      L'email est requis
                    </mat-error>
                    <mat-error *ngIf="profileForm.get('email')?.hasError('email')">
                      L'email n'est pas valide
                    </mat-error>
                  </mat-form-field>

                  <mat-form-field appearance="outline">
                    <mat-label>Rôle</mat-label>
                    <input matInput formControlName="role" readonly>
                    <mat-icon matSuffix>security</mat-icon>
                  </mat-form-field>
                </div>

                <div class="form-column">
                  <mat-form-field appearance="outline">
                    <mat-label>Ancien mot de passe</mat-label>
                    <input matInput type="password" formControlName="oldPassword" 
                           placeholder="Entrez votre ancien mot de passe">
                    <mat-icon matSuffix>lock</mat-icon>
                  </mat-form-field>

                  <mat-form-field appearance="outline">
                    <mat-label>Nouveau mot de passe</mat-label>
                    <input matInput type="password" formControlName="newPassword" 
                           placeholder="Entrez votre nouveau mot de passe">
                    <mat-icon matSuffix>lock_open</mat-icon>
                  </mat-form-field>

                  <div class="form-field">
                    <label class="form-label">Avatar</label>
                    <input type="file" accept="image/*" (change)="onFileSelected($event)" class="file-input">
                  </div>

                  <div class="current-avatar" *ngIf="currentAvatarUrl">
                    <label class="form-label">Avatar actuel</label>
                    <img [src]="currentAvatarUrl" alt="Avatar actuel" class="avatar-large">
                  </div>
                </div>
              </div>

              <div class="button-container">
                <button mat-raised-button color="primary" type="submit" [disabled]="profileForm.invalid || loading">
                  <mat-icon>{{ loading ? 'hourglass_empty' : 'save' }}</mat-icon>
                  {{ loading ? 'Enregistrement...' : 'Enregistrer' }}
                </button>
              </div>
            </form>
          </mat-card-content>
        </mat-card>
      </div>
    </div>
  `,
  styles: [
    `
    .form-container {
      max-width: 800px;
      margin: 0 auto;
    }

    .form-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 32px;
      margin-bottom: 24px;
    }

    .form-column {
      display: flex;
      flex-direction: column;
      gap: 16px;
    }

    .form-field {
      margin-bottom: 16px;
    }

    .form-label {
      display: block;
      font-weight: 500;
      margin-bottom: 8px;
      color: rgba(0, 0, 0, 0.6);
    }

    .file-input {
      width: 100%;
      padding: 12px;
      border: 2px dashed #ddd;
      border-radius: 8px;
      background-color: #fafafa;
      cursor: pointer;
    }

    .file-input:hover {
      border-color: #ccc;
      background-color: #f5f5f5;
    }

    .current-avatar {
      text-align: center;
    }

    .avatar-large {
      width: 80px;
      height: 80px;
      border-radius: 50%;
      object-fit: cover;
      border: 3px solid white;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
    }

    .button-container {
      display: flex;
      gap: 16px;
      justify-content: flex-end;
      margin-top: 24px;
    }

    @media (max-width: 768px) {
      .form-grid {
        grid-template-columns: 1fr;
        gap: 16px;
      }

      .button-container {
        flex-direction: column;
      }

      .button-container button {
        width: 100%;
      }
    }
  `,
  ],
})
export class ProfileComponent implements OnInit {
  profileForm: FormGroup
  loading = false
  selectedFile: File | null = null
  currentAvatarUrl: string | null = null

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private snackBar: MatSnackBar,
  ) {
    this.profileForm = this.fb.group({
      login: [""],
      email: ["", [Validators.required, Validators.email]],
      role: [""],
      oldPassword: [""],
      newPassword: [""],
    })
  }

  ngOnInit() {
    const user = this.authService.getCurrentUser()
    if (user) {
      this.profileForm.patchValue({
        login: user.login,
        email: user.email,
        role: user.role === "ADMIN" ? "Administrateur" : "Visiteur",
      })

      if (user.avatar) {
        this.currentAvatarUrl = `assets/images/${user.avatar}`
      }
    }
  }

  onFileSelected(event: Event) {
    const target = event.target as HTMLInputElement
    if (target.files && target.files.length > 0) {
      this.selectedFile = target.files[0]

      // Prévisualisation de l'image
      const reader = new FileReader()
      reader.onload = (e) => {
        this.currentAvatarUrl = e.target?.result as string
      }
      reader.readAsDataURL(this.selectedFile)
    }
  }

  onSubmit() {
    if (this.profileForm.valid) {
      this.loading = true

      const formData = this.profileForm.value

      // Validation des mots de passe
      if (formData.newPassword && !formData.oldPassword) {
        this.snackBar.open("Veuillez entrer votre ancien mot de passe", "Fermer", {
          duration: 3000,
          panelClass: ["error-snackbar"],
        })
        this.loading = false
        return
      }

      // Simulation de la mise à jour
      setTimeout(() => {
        this.loading = false

        // Mettre à jour les données utilisateur
        this.authService.updateProfile({ email: formData.email })

        this.snackBar.open("Profil mis à jour avec succès!", "Fermer", {
          duration: 3000,
          panelClass: ["success-snackbar"],
        })

        // Réinitialiser les champs de mot de passe
        this.profileForm.patchValue({
          oldPassword: "",
          newPassword: "",
        })
      }, 1000)
    }
  }
}

// app/profile/page.tsx
"use client"

import type React from "react"

import { useState, useEffect } from "react"
import { useAuth } from "@/components/auth-provider"
import { Navigation } from "@/components/navigation"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Save } from "lucide-react"
import { useRouter } from "next/navigation"

export default function ProfilePage() {
  const { user, updateProfile } = useAuth()
  const router = useRouter()
  const [formData, setFormData] = useState({
    email: "",
    oldPassword: "",
    newPassword: "",
    avatar: null as File | null,
  })
  const [message, setMessage] = useState("")
  const [error, setError] = useState("")
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    if (!user) {
      router.push("/")
      return
    }

    setFormData((prev) => ({
      ...prev,
      email: user.email,
    }))
  }, [user, router])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setError("")
    setMessage("")

    try {
      // Validation des mots de passe
      if (formData.newPassword && !formData.oldPassword) {
        setError("Veuillez entrer votre ancien mot de passe")
        return
      }

      // Simulation de la mise à jour du profil
      await new Promise((resolve) => setTimeout(resolve, 1000))

      // Mettre à jour les données utilisateur
      updateProfile({ email: formData.email })

      setMessage("Profil mis à jour avec succès!")

      // Réinitialiser les champs de mot de passe
      setFormData((prev) => ({
        ...prev,
        oldPassword: "",
        newPassword: "",
      }))
    } catch (err) {
      setError("Erreur lors de la mise à jour du profil")
    } finally {
      setLoading(false)
    }
  }

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0] || null
    setFormData({ ...formData, avatar: file })
  }

  if (!user) return null

  return (
    <div className="min-h-screen bg-gray-50">
      <Navigation />

      <div className="max-w-4xl mx-auto py-6 sm:px-6 lg:px-8">
        <div className="px-4 py-6 sm:px-0">
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-gray-900">Mon profil</h1>
            <p className="mt-2 text-gray-600">Gérez vos informations personnelles et paramètres de compte</p>
          </div>

          <Card>
            <CardHeader>
              <CardTitle>Informations du profil</CardTitle>
            </CardHeader>
            <CardContent>
              {message && (
                <Alert className="mb-4">
                  <AlertDescription>{message}</AlertDescription>
                </Alert>
              )}

              {error && (
                <Alert className="mb-4" variant="destructive">
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              )}

              <form onSubmit={handleSubmit} className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="login">Login</Label>
                      <Input id="login" value={user.login} disabled className="bg-gray-50" />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="email">Email *</Label>
                      <Input
                        id="email"
                        type="email"
                        value={formData.email}
                        onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                        required
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="role">Rôle</Label>
                      <Input id="role" value={user.role} disabled className="bg-gray-50" />
                    </div>
                  </div>

                  <div className="space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="oldPassword">Ancien mot de passe</Label>
                      <Input
                        id="oldPassword"
                        type="password"
                        value={formData.oldPassword}
                        onChange={(e) => setFormData({ ...formData, oldPassword: e.target.value })}
                        placeholder="Entrez votre ancien mot de passe"
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="newPassword">Nouveau mot de passe</Label>
                      <Input
                        id="newPassword"
                        type="password"
                        value={formData.newPassword}
                        onChange={(e) => setFormData({ ...formData, newPassword: e.target.value })}
                        placeholder="Entrez votre nouveau mot de passe"
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="avatar">Avatar</Label>
                      <Input id="avatar" type="file" accept="image/*" onChange={handleFileChange} />
                    </div>

                    <div className="space-y-2">
                      <Label>Avatar actuel</Label>
                      <Avatar className="h-20 w-20">
                        <AvatarImage src={user.avatar ? `/images/${user.avatar}` : undefined} />
                        <AvatarFallback className="text-lg">{user.login.charAt(0).toUpperCase()}</AvatarFallback>
                      </Avatar>
                    </div>
                  </div>
                </div>

                <Button type="submit" disabled={loading}>
                  <Save className="h-4 w-4 mr-2" />
                  {loading ? "Enregistrement..." : "Enregistrer"}
                </Button>
              </form>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
